airports = [
    "Aberdeen (ABZ)",
    "Abu Dhabi (AUH)",
    "Agadir (AGA)",
    "Alesund (AES)",
    "Alexandria (Borg El Arab) (HBE)",
    "Alghero (Sardinia) (AHO)",
    "Alicante (ALC)",
    "Almaty (ALA)",
    "Amman (AMM)",
    "Ancona (AOI)",
    "Antalya (AYT)",
    "Aqaba (AQJ)",
    "Astana (NQZ)",
    "Athens (ATH)",
    "Bacau (BCM)",
    "Baku (GYD)",
    "Banja Luka (BNX)",
    "Barcelona El Prat (BCN)",
    "Bari (BRI)",
    "Basel-Mulhouse-Freiburg (MLH)",
    "Basel-Mulhouse-Freiburg (BSL)",
    "Belgrad (BEG)",
    "Bergen (BGO)",
    "Berlin Brandenburg (BER)",
    "Bilbao (BIO)",
    "Billund (BLL)",
    "Birmingham (BHX)",
    "Bishkek (FRU)",
    "Bologna (BLQ)",
    "Bourgas (Black Sea) (BOJ)",
    "Brasov (GHV)",
    "Bratislava (BTS)",
    "Bremen (BRE)",
    "Brindisi (BDS)",
    "Brussels (BRU)",
    "Brussels Charleroi (CRL)",
    "Bucharest (OTP)",
    "Bucharest Baneasa (BBU)",
    "Budapest (BUD)",
    "Cairo (Sphinx) (SPX)",
    "Castellon (Valencia) (CDT)",
    "Catania (Sicily) (CTA)",
    "Chania (Crete) (CHQ)",
    "Chisinau (RMO)",
    "Cluj-Napoca (CLJ)",
    "Cologne (CGN)",
    "Comiso (CIY)",
    "Constanta (CND)",
    "Copenhagen (CPH)",
    "Corfu (CFU)",
    "Craiova (CRA)",
    "Dalaman (DLM)",
    "Dammam (DMM)",
    "Debrecen (DEB)",
    "Dortmund (DTM)",
    "Dubai (DXB)",
    "Dubrovnik (DBV)",
    "Eindhoven (EIN)",
    "Erbil (EBL)",
    "Faro (FAO)",
    "Frankfurt Hahn (HHN)",
    "Friedrichshafen (FDH)",
    "Fuerteventura (Canary Islands) (FUE)",
    "Funchal (Madeira) (FNC)",
    "Gabala (GBB)",
    "Gdansk (GDN)",
    "Geneva (GVA)",
    "Genoa (GOA)",
    "Girona (GRO)",
    "Glasgow (GLA)",
    "Gothenburg Landvetter (GOT)",
    "Gran Canaria (Canary Islands) (LPA)",
    "Grenoble (GNB)",
    "Hamburg (HAM)",
    "Haugesund (HAU)",
    "Heraklion (Crete) (HER)",
    "Hurghada (HRG)",
    "Iasi (IAS)",
    "Ibiza (IBZ)",
    "Istanbul (IST)",
    "Izmir (ADB)",
    "Jeddah (JED)",
    "Karlsruhe/Baden-Baden (FKB)",
    "Katowice (KTW)",
    "Kaunas (KUN)",
    "Kefalonia (EFL)",
    "Kos (KGS)",
    "Kosice (KSC)",
    "Kraków (KRK)",
    "Kutaisi (KUT)",
    "Larnaca (LCA)",
    "Leeds (LBA)",
    "Leipzig (LEJ)",
    "Lisbon (LIS)",
    "Liverpool (LPL)",
    "Ljubljana (LJU)",
    "London Gatwick (LGW)",
    "London Luton (LTN)",
    "Lublin (LUZ)",
    "Lyon (LYS)",
    "Maastricht (MST)",
    "Madinah (MED)",
    "Madrid (MAD)",
    "Malaga (AGP)",
    "Malé (Maldives) (MLE)",
    "Malmo (MMX)",
    "Malta (MLA)",
    "Marrakesh (RAK)",
    "Marsa Alam (RMF)",
    "Memmingen/Munich West (FMM)",
    "Milan Bergamo (BGY)",
    "Milan Malpensa (MXP)",
    "Muscat (MCT)",
    "Mykonos (JMK)",
    "Naples (NAP)",
    "Nice (NCE)",
    "Niš (INI)",
    "Nuremberg (NUE)",
    "Ohrid (OHD)",
    "Olbia (Sardinia) (OLB)",
    "Olsztyn-Mazury (SZY)",
    "Oslo Gardermoen (OSL)",
    "Oslo Sandefjord Airport (TRF)",
    "Palanga (PLQ)",
    "Palma de Mallorca (PMI)",
    "Paphos (PFO)",
    "Paris Beauvais (BVA)",
    "Paris Orly (ORY)",
    "Perugia (PEG)",
    "Pescara (PSR)",
    "Pisa (Tuscany) (PSA)",
    "Plovdiv (PDV)",
    "Podgorica (TGD)",
    "Poprad-Tatry (TAT)",
    "Porto (OPO)",
    "Poznan (POZ)",
    "Prague (PRG)",
    "Prishtina (PRN)",
    "Radom (RDO)",
    "Rafic Hariri Intl (BEY)",
    "Reykjavik (KEF)",
    "Rhodes (RHO)",
    "Riga (RIX)",
    "Rimini (RMI)",
    "Riyadh (RUH)",
    "Rome Ciampino (CIA)",
    "Rome Fiumicino (FCO)",
    "Rovaniemi (RVN)",
    "Rzeszów (RZE)",
    "Salalah (SLL)",
    "Salerno Costa d'Amalfi (QSR)",
    "Salzburg (SZG)",
    "Samarkand (SKD)",
    "Santander (SDR)",
    "Santorini (JTR)",
    "Sarajevo (SJJ)",
    "Satu Mare (SUJ)",
    "Seville (SVQ)",
    "Sharm El Sheikh (SSH)",
    "Sibiu (SBZ)",
    "Skiathos (JSI)",
    "Skopje (SKP)",
    "Sofia (SOF)",
    "Sohag (HMB)",
    "Split (SPU)",
    "Stavanger (SVG)",
    "Stockholm Arlanda (ARN)",
    "Stockholm Skavsta (NYO)",
    "Stuttgart (STR)",
    "Suceava (SCV)",
    "Szczecin (SZZ)",
    "Tallinn (TLL)",
    "Tashkent (TAS)",
    "Tel-Aviv (TLV)",
    "Tenerife (Canary Islands) (TFS)",
    "Thessaloniki (SKG)",
    "Timisoara (TSR)",
    "Tirana (TIA)",
    "Tirgu Mures (TGM)",
    "Trieste (TRS)",
    "Tromso (TOS)",
    "Trondheim (TRD)",
    "Turin (TRN)",
    "Turkistan (HSA)",
    "Turku (TKU)",
    "Tuzla (TZL)",
    "Valencia (VLC)",
    "Varna (Black Sea) (VAR)",
    "Venice Marco Polo (VCE)",
    "Venice Treviso (TSF)",
    "Verona (VRN)",
    "Vienna (VIE)",
    "Vilnius (VNO)",
    "Warsaw Chopin (WAW)",
    "Wroclaw (WRO)",
    "Yerevan (EVN)",
    "Zakynthos (ZTH)",
    "Zaragoza (ZAZ)",
]