spring.application.name=flightFinder
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss} \u001B[32m%-5level \u001B[0m - %msg \u001B[36m[%class.%method:%line]\u001B[0m%n
#logging.file.name=messages.log
#logging.pattern.file=%d{yyyy-MM-dd'T'HH:mm:ss} %-5level - %msg [%class.%method:%line]%n
# Enable Prometheus endpoint
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=read_only
management.prometheus.metrics.export.enabled=true
management.graphite.metrics.export.enabled=true
